[theme]
base = "light"
primaryColor = "#13798c"
backgroundColor = "#f4f7fa"
secondaryBackgroundColor = "#e8eff3"
textColor = "#122b39"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
headless = true
